
CREATE TABLE Categoria (CODIGO INT PRIMARY KEY, NOME VARCHAR(64) NOT NULL, DEVOLUCAO INT NOT NULL);

CREATE TABLE Usuario (CODIGO INT PRIMARY KEY, NOME VARCHAR(64) NOT NULL,  SEXO BOOLEAN NOT NULL, ENDERECO VARCHAR(128) NOT NULL, TELEFONE VARCHAR(11) NOT NULL, CODIGOCATEGORIA INT NOT NULL, FOREIGN KEY(CODIGOCATEGORIA) REFERENCES Categoria(CODIGO));

CREATE TABLE Multa (CODIGO INT PRIMARY KEY, CODIGOUSUARIO INT NOT NULL, DESCRICAO VARCHAR(64) NOT NULL, VALOR DOUBLE NOT NULL, FOREIGN KEY(CODIGOUSUARIO) REFERENCES Usuario(CODIGO));

CREATE TABLE Livro (CODIGO INT PRIMARY KEY,  TITULO VARCHAR(64) NOT NULL, PRIORIDADE INT NOT NULL, CATEGORIA VARCHAR(64), ANO INT NOT NULL, DISPONIBILIDADE BOOLEAN NOT NULL);

CREATE TABLE Emprestimo (CODIGO INT PRIMARY KEY, DATAEMPRESTIMO DATE NOT NULL, DATADEVOLUCAO DATE DEFAULT NULL, CODIGOLIVRO INT NOT NULL, CODIGOUSUARIO INT NOT NULL, FOREIGN KEY(CODIGOLIVRO) REFERENCES Livro(CODIGO), FOREIGN KEY(CODIGOUSUARIO) REFERENCES Usuario(CODIGO));

CREATE TABLE Autor (CODIGO INT PRIMARY KEY, NOME VARCHAR(64) NOT NULL);

CREATE TABLE LivroAutor (CODIGOLIVRO INT, CODIGOAUTOR INT, PRIMARY KEY(CODIGOLIVRO, CODIGOAUTOR), FOREIGN KEY(CODIGOLIVRO) REFERENCES Livro(CODIGO), FOREIGN KEY(CODIGOAUTOR) REFERENCES Autor(CODIGO));
